//Types for Login
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

//Types for Sign up
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Types for Charge user balance up
export const CHARGE_BALANCE_REQUEST = 'CHARGE_BALANCE_REQUEST';
export const CHARGE_BALANCE_SUCCESS = 'CHARGE_BALANCE_SUCCESS';
export const CHARGE_BALANCE_FAILURE = 'CHARGE_BALANCE_FAILURE';

//Type for Forgot

export const FORGOT_REQUEST_REQUEST = 'FORGOT_REQUEST_REQUEST';
export const FORGOT_REQUEST_DIGITS = 'FORGOT_REQUEST_DIGITS';
export const FORGOT_PASSWORD_UPDATE_REQUEST = 'FORGOT_PASSWORD_UPDATE_REQUEST';

//Type for Logout

export const LOGOUT_REQUEST_REQUEST = 'LOGOUT_REQUEST_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';

// loading
export const SET_AUTH_LOADER = 'SET_AUTH_LOADER';

//Types for Login
export const MAINTENANCE_FLAG_REQUEST = 'MAINTENANCE_FLAG_REQUEST';
export const MAINTENANCE_FLAG_SUCCESS = 'MAINTENANCE_FLAG_SUCCESS';

//Types for GET USER WALLET
export const GET_USER_WALLET_REQUEST = 'GET_USER_WALLET_REQUEST';
export const GET_USER_WALLET_SUCCESS = 'GET_USER_WALLET_SUCCESS';
export const GET_USER_SUMMARY_WALLET_SUCCESS = 'GET_USER_SUMMARY_WALLET_SUCCESS';
export const GET_USER_WALLET_FAILURE = 'GET_USER_WALLET_FAILURE';

//Types for UPDATE USER BIOMETRICS KEY
export const UPDATE_USER_BIOMETRICS_KEY_REQUEST = 'UPDATE_USER_BIOMETRICS_KEY_REQUEST';
