// types for store
export const GET_STORES_REQUEST = 'GET_STORES_REQUEST';
export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS';
export const GET_STORES_FAILURE = 'GET_STORES_FAILURE';
export const GET_STORE_REQUEST = 'GET_STORE_REQUEST';
export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS';

// types for wallet eligible
export const GET_WALLET_ELIGIBLE_REQUEST = 'GET_WALLET_ELIGIBLE_REQUEST';
export const GET_WALLET_ELIGIBLE_SUCCESS = 'GET_WALLET_ELIGIBLE_SUCCESS';
export const GET_WALLET_ELIGIBLE_FAILURE = 'GET_WALLET_ELIGIBLE_FAILURE';

// types for convert order
export const CONVERT_ORDER_REQUEST = 'CONVERT_ORDER_REQUEST';

// types for Orders
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';
export const UPDATE_ORDER = 'UPDATE_ORDER'; 
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';

// loading
export const SET_ORDER_LOADER = 'SET_ORDER_LOADER';

//cart
export const GET_CART_REQUEST = 'GET_CART_REQUEST'; 
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';

export const PAID_REQUEST = 'PAID_REQUEST';

export const GET_ZAIN_REQUEST = 'GET_ZAIN_REQUEST'; 
export const GET_ZAIN_SUCCESS = 'GET_ZAIN_SUCCESS';
export const GET_ZAIN_FAILURE = 'GET_ZAIN_FAILURE';

export const UPDATE_ZAIN_REQUEST = 'UPDATE_ZAIN_REQUEST';
export const INITIALIZE_ZAIN_REQUEST = 'INITIALIZE_ZAIN_REQUEST';
export const GENERATE_ZAIN_REQUEST = 'GENERATE_ZAIN_REQUEST';

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST'; 
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';

export const GET_COUPON_CODE_REQUEST = 'GET_COUPON_CODE_REQUEST'; 